PROJECT_NAME: medpoint
PROJECT_ID: iwbmcpwszaalactwhfiy
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_4e2cafacbfb4300b715a984e20b2e78fa8cdd140
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3Ym1jcHdzemFhbGFjdHdoZml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMDg0NzcsImV4cCI6MjA1MTg4NDQ3N30.YyJX3LwdYinHVcBsjlzDuYLhnUSB41uLRvyeRfCgnuE
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3Ym1jcHdzemFhbGFjdHdoZml5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNjMwODQ3NywiZXhwIjoyMDUxODg0NDc3fQ.UAENZAy5C2YRrEz3k4BMbUYeI9UiEHwID0EKUDNj3z8

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://iwbmcpwszaalactwhfiy.supabase.co

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
